version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 3165:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/html
  yvm:
    build: .
    volumes:
      - ./classes:/var/www/html/classes
    hostname: yvm
    container_name: yvm-service
