#!/usr/bin/env bash
#
# based on git's pre-commit.sample

# Redirect output to stderr.
exec 1>&2

if ! grep "$(git rev-parse main)" <(git rev-list fixed~5..fixed) > /dev/null
then
	echo please rebase fixed onto main.
	exit 1
fi
